version: '3.8'

services:
  customer-service:
    build: ./customer-service/customer-service
    container_name: customer-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/userDB"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - contract-signing-network
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/localhost/8080' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  credential-generation:
    build:
      context: ./credential-generation
      dockerfile: Dockerfile
    container_name: credential-generation
    ports:
      - "8082:8082"
    networks:
      - contract-signing-network
    depends_on:
      customer-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/localhost/8082' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  exhibition-service:
    build:
      context: ./Exhibition-service
      dockerfile: Dockerfile
    container_name: exhibition-service
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://exhibition-db:5432/exhibitionDB"
      SPRING_DATASOURCE_USERNAME: "exhibition_user"
      SPRING_DATASOURCE_PASSWORD: "exhibition_password"
    depends_on:
      exhibition-db:
        condition: service_healthy
    networks:
      - contract-signing-network
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/localhost/8084' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mail-service:
    build:
      context: ./mail-service
      dockerfile: Dockerfile
    container_name: mail-service
    ports:
      - "8083:8083"
    environment:
      - SIMULATION_MODE=false
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USE_TLS=true
      - SMTP_USERNAME=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
      - DEFAULT_FROM_EMAIL=noreply@contractsigning.com
    networks:
      - contract-signing-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8083/api/mail/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:latest
    container_name: customer-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d userDB" ]
      interval: 10s
      retries: 3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userDB
    ports:
      - "5432:5432"
    networks:
      - contract-signing-network

  exhibition-db:
    image: postgres:latest
    container_name: exhibition-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U exhibition_user -d exhibitionDB" ]
      interval: 10s
      retries: 3
    environment:
      POSTGRES_USER: exhibition_user
      POSTGRES_PASSWORD: exhibition_password
      POSTGRES_DB: exhibitionDB
    ports:
      - "5433:5432"
    networks:
      - contract-signing-network

networks:
  contract-signing-network:
    driver: bridge 