version: '3.8'

services:
  credential-generation:
    build: .
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - contract-signing-network

networks:
  contract-signing-network:
    external: true 